name: AndroidAPS CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: '0 0 */14 * *'  # 每14天自动构建

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      STORE_FILE: keystore/release.keystore
      CI: true  # 标识CI环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Prepare Keystore
        run: |
          mkdir -p keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > $STORE_FILE
          if [ ! -s $STORE_FILE ]; then
            echo "::error::Keystore file is invalid or empty"
            exit 1
          fi

      - name: Build Release APK
        run: ./gradlew assembleFullRelease
        env:
          STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidAPS-Release
          path: app/build/outputs/apk/full/release/*.apk
          retention-days: 7

      - name: Cleanup
        run: rm -rf keystore
        if: always()
