name: Build AndroidAPS

on:
  push:
  schedule:
    - cron: '0 8 * * *'  # 每天 UTC 时间 08:00 自动检查上游更新
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      STORE_FILE: my-release-key.jks

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Pull upstream changes
        run: |
          git remote add upstream https://github.com/nightscout/AndroidAPS.git
          git fetch upstream
          git merge upstream/master --allow-unrelated-histories -m "Auto-merge from upstream"
          git push origin HEAD:master

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > $STORE_FILE

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleFullRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidAPS-FullRelease
          path: app/build/outputs/apk/full/release/*.apk
