name: Sync & Build AAPS

on:
  schedule:
    - cron: '0 0 */14 * *'  # 每14天 UTC 时间 00:00 自动触发（约等于北京时间 08:00）
  workflow_dispatch:         # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Setup Git Identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add upstream and merge
        run: |
          git remote add upstream https://github.com/nightscout/AndroidAPS.git
          git fetch upstream
          git merge upstream/master --no-ff --no-commit || true
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore: merge upstream updates"
          fi

      - name: Setup Java & Gradle
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - uses: gradle/gradle-build-action@v2

      - name: Make Gradlew executable
        run: chmod +x gradlew

      - name: Restore Keystore
        run: |
          mkdir -p keystore
          echo "${{ secrets.STORE_FILE }}" | tr -d '\n\r ' | base64 --decode > keystore/demokeystore.jks
          FILE_SIZE=$(wc -c < keystore/demokeystore.jks)
          echo "Keystore size: $FILE_SIZE bytes"
          if [ ! -f keystore/demokeystore.jks ] || [ "$FILE_SIZE" -lt 1000 ]; then
            echo "Invalid or too small keystore"
            exit 1
          fi

      - name: Build Release APK
        run: ./gradlew assembleFullRelease
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_FILE: keystore/demokeystore.jks
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidAPS-Release
          path: app/build/outputs/**/*.apk

      - name: Cleanup Keystore
        if: ${{ always() }}
        run: rm -f keystore/demokeystore.jks
