name: Sync & Build AAPS

on:
  schedule:
    - cron: '0 0 */14 * *'  # 每 14 天自动触发（UTC 0 点）
  workflow_dispatch:       # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Add upstream and merge
        run: |
          git remote add upstream https://github.com/nightscout/AndroidAPS.git
          git fetch upstream
          git merge upstream/master --no-ff --no-commit || true
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore: merge upstream updates"
          fi

      - name: Setup Java & Gradle
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - uses: gradle/gradle-build-action@v2

      - name: Make Gradlew executable
        run: chmod +x gradlew

      - name: Restore Keystore
        run: |
          mkdir -p keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore/demokeystore.jks
          FILE_SIZE=$(wc -c < keystore/demokeystore.jks)
          echo "Keystore size: $FILE_SIZE bytes"
          if [ ! -f keystore/demokeystore.jks ] || [ "$FILE_SIZE" -lt 1000 ]; then
            echo "Invalid or too small keystore"
            exit 1
          fi

      - name: Build Release APK
        run: ./gradlew assembleFullRelease
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          # build.gradle 中引用 storeFile 需要的是文件路径
          # 所以直接写死路径
          STORE_FILE: keystore/demokeystore.jks

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidAPS-Release
          path: app/build/outputs/**/*.apk

      - name: Cleanup Keystore
        if: ${{ always() }}
        run: rm -f keystore/demokeystore.jks
