name: Sync Upstream & Auto Build

on:
  schedule:
    - cron: '0 0 */14 * *'  # 每14天 UTC 0点触发
  workflow_dispatch:         # 支持手动触发

jobs:
  sync-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Add Upstream and Merge
        run: |
          git remote add upstream https://github.com/diyaps/AndroidAPS.git
          git fetch upstream
          git merge upstream/master --allow-unrelated-histories -m "Merge upstream"

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Restore Keystore File
        run: |
          mkdir -p keystore
          echo "Restoring keystore from base64..."
          echo "${{ secrets.STORE_FILE }}" | tr -d '\n\r ' | base64 -d > keystore/demokeystore.jks

          FILE_SIZE=$(wc -c < keystore/demokeystore.jks)
          echo "Keystore file size: $FILE_SIZE bytes"

          if [ ! -f "keystore/demokeystore.jks" ] || [ "$FILE_SIZE" -lt 100 ]; then
            echo "❌ Keystore file not created or too small"
            exit 1
          fi
          echo "✅ Keystore restored successfully"

      - name: Print Keystore Info (Debug)
        run: |
          keytool -list -keystore keystore/demokeystore.jks -storepass "${{ secrets.STORE_PASSWORD }}" || true

      - name: Build APK (assembleFullRelease)
        run: ./gradlew assembleFullRelease --no-build-cache
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          STORE_FILE: keystore/demokeystore.jks

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AndroidAPS-FullRelease-APK
          path: app/build/outputs/apk/full/release/*.apk
