name: Sync Upstream & Auto Build

on:
  schedule:
    - cron: '0 0 */14 * *'  # 每14天触发一次（UTC 0点）
  workflow_dispatch:       # 手动触发

jobs:
  sync-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Add Upstream and Fetch
        run: |
          git remote add upstream https://github.com/diyaps/AndroidAPS.git
          git fetch upstream
          git merge upstream/master --no-ff --no-commit || true
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Merge upstream with conflicts"
          fi

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Restore Keystore File
        run: |
          mkdir -p keystore
          echo "Restoring keystore from base64..."
          
          # 清理base64字符串
          CLEAN_BASE64=$(echo "${{ secrets.STORE_FILE }}" | tr -d '\n\r ')
          echo "$CLEAN_BASE64" | base64 --decode > keystore/demokeystore.jks
          
          # 增强文件校验
          FILE_SIZE=$(wc -c < keystore/demokeystore.jks)
          echo "Keystore file size: $FILE_SIZE bytes"
          
          if [ ! -f "keystore/demokeystore.jks" ] || [ "$FILE_SIZE" -lt 1000 ]; then
            echo "❌ Keystore file invalid or too small (min 1000 bytes)"
            exit 1
          fi
          
          echo "✅ Keystore restored successfully"

      - name: Build Release APK
        run: ./gradlew assembleFullRelease
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_FILE: keystore/demokeystore.jks
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AndroidAPS-Release-APK
          path: app/build/outputs/apk/full/release/*.apk
          
      - name: Clean up workspace
        if: ${{ always() }}
        run: |
          # 仅在成功构建后删除密钥库
          if [ -z "${{ job.status }}" ] || [ "${{ job.status }}" == "success" ]; then
            rm -f keystore/demokeystore.jks
            echo "✅ Keystore removed"
          else
            echo "⚠️ 构建失败，保留密钥库用于调试"
          fi
